### ISSUE TITLE
OpenSSL 3 deprecated RIPEMD160 ("legacy feature")

### ISSUE THREAD

**Issue by seb-sykio** [GemHQ/money-tree#62]
on ubuntu 20 with openssl 1.1 everything is ok
on ubuntu 22, since july 8th, with OpenSSL 3.0.2 15 Mar 2022 (Library: OpenSSL 3.0.2 15 Mar 2022), I have this error

     OpenSSL::Digest::DigestError:
       Digest initialization failed: initialization error
     # .rvm/gems/ruby-3.1.2@gems/money-tree-0.10.0/lib/money-tree/support.rb:62:in `digestify'
     # .rvm/gems/ruby-3.1.2@gems/money-tree-0.10.0/lib/money-tree/support.rb:70:in `ripemd160'
     # .rvm/gems/ruby-3.1.2@gems/money-tree-0.10.0/lib/money-tree/key.rb:246:in `to_ripemd160'
     # .rvm/gems/ruby-3.1.2@gems/money-tree-0.10.0/lib/money-tree/node.rb:130:in `to_identifier'
     # .rvm/gems/ruby-3.1.2@gems/money-tree-0.10.0/lib/money-tree/node.rb:146:in `to_address'
     # .rvm/gems/ruby-3.1.2@bundler/gems/cryptocoin_payable-776b48475f73/lib/cryptocoin_payable/adapters/bitcoin.rb:20:in `create_address'

**Comment by bdescamps** [comment]
Hello,
ripemd160 is deal as legacy on openssl 3.0, you can activate it through openssl config file.
Take a look at this : https://github.com/ethereum/execution-specs/issues/506

**Comment by q9f** [comment]
Good find. Wondering if we can find alternatives to OpenSSL in this case. I don't think explaining every user to enable legacy features in their OS configuration of OpenSSL is a viable option here.

**Comment by bdescamps** [comment]
Maybe we could deal that into 2 steps : 
 -  Detect and inform user that feature is not enabled and a way to activate (quick to implement) 
 -  Override the inital config, when using the gem ( best solution more work)

**Comment by q9f** [comment]
> * Detect and inform user that feature is not enabled and a way to activate (quick to implement)

What did you have in mind? Like, catching an `OpenSSL::Digest::DigestError` and suggest to reinstall OpenSSL with RIPEMD160?

**Comment by bdescamps** [comment]
Yes, that's it. That does not require a reinstall of openssl just a config legacy_sect activation.
I have done the work here for CI : https://github.com/debreczeni/money-tree/pull/2/files

**Comment by q9f** [comment]
Ripemd160 was added back into the default providers list. So best we can do now is wait. Don't think we should fix this on the level of this library.

https://www.openssl.org/blog/blog/2022/10/18/rmd160-and-the-legacy-provider

**Comment by q9f** [comment]
RIPEMD is back in openssl 3.0.7 - no action required.

**Comment by sbounmy** [comment]
having the same issue here on Github Action CI

upgraded to openssl 3.2.0 with https://orcacore.com/install-latest-openssl-ubuntu-22-04/ didn't fix it.
```yaml
# githubactions.yml
      - name: Upgrade openssl
        run: |
          openssl version -a
          sudo apt-get install checkinstall zlib1g-dev -y
          wget https://github.com/openssl/openssl/releases/download/openssl-3.2.0/openssl-3.2.0.tar.gz -O openssl-3.2.0.tar.gz
          tar xvf openssl-3.2.0.tar.gz
          cd openssl-3.2.0/
          sudo ./config
          sudo make
          sudo make test
          sudo make install
          sudo ldconfig
          sudo tee /etc/profile.d/openssl.sh<<EOF
            export PATH=/usr/local/openssl/bin:\$PATH
            export LD_LIBRARY_PATH=/usr/local/openssl/lib:\$LD_LIBRARY_PATH
          EOF
          source /etc/profile.d/openssl.sh
          openssl version -a
```
```sh
OpenSSL 3.2.0 23 Nov 2023 (Library: OpenSSL 3.2.0 23 Nov 2023)
built on: Tue Jan  9 22:39:52 2024 UTC
platform: linux-x86_64
options:  bn(64,64)
compiler: gcc -fPIC -pthread -m64 -Wa,--noexecstack -Wall -O3 -DOPENSSL_USE_NODELETE -DL_ENDIAN -DOPENSSL_PIC -DOPENSSL_BUILDING_OPENSSL -DNDEBUG
OPENSSLDIR: "/usr/local/ssl"
ENGINESDIR: "/usr/local/lib64/engines-3"
MODULESDIR: "/usr/local/lib64/ossl-modules"
Seeding source: os-specific
CPUINFO: OPENSSL_ia32cap=0xfeda32034f8bffff:0xd09f2fb9
```
Still investigating...

**Comment by ryenski** [comment]
@sbounmy were you able to resolve this issue?

**Comment by sbounmy** [comment]
@ryenski what I see from my commit history I switched on butuntu-24.04 with libsssl-dev pkg

```yml
jobs:
   test:
     runs-on: ubuntu-24.04
      steps:
      - name: Install packages
         run: |
           sudo apt-get update
           sudo apt-get install -y --fix-missing 
             libffi-dev libssl-dev libgmp-dev python3-dev
```

However I am not sure because I havent worked on that project for a while

**Comment by ryenski** [comment]
I was able to get it to work by including a config for openssl: 
```yml
jobs:
  test:
    steps:
      - name: Set up OpenSSL with legacy provider
        run: |
          echo "OPENSSL_CONF=$GITHUB_WORKSPACE/config/openssl.cnf" >> $GITHUB_ENV
```
```cnf
openssl_conf = openssl_init

[openssl_init]
providers = provider_sect

[provider_sect]
default = default_sect
legacy = legacy_sect

[default_sect]
activate = 1

[legacy_sect]
activate = 1
```
